name: Java CI with Gradle

on:
  push:
    branches: [ "kryatenkova" ]
  pull_request:
    branches: [ "kryatenkova" ]
  schedule:
    - cron: '30 12 * * 3'
    - cron: '0 22 * * 5'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: [11, 13, 17]
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Install JDK 13
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-13-jdk
        echo "JAVA_HOME=/usr/lib/jvm/java-13-openjdk-amd64" >> $GITHUB_ENV

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Clean Gradle cache
      run: ./gradlew clean

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
